version: '3.8'

services:

  mysql-db:
    container_name:  mysql-db
    image: mysql:8.2
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_PASSWORD
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - mysqldb:/var/lib/mysql:rw
      - ./mysqldb:/docker-entrypoint-initdb.d/
    networks:
      - default

  dashboard:
    container_name: dashboard
    # depends_on: 
      # - nestjs-app
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NEXTJS_APP_LOCAL_PORT:$NEXTJS_APP_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./dashboard:/app
      - /app/node_modules
      - /app/.next
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  mysqldb: {}